version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: gin-api
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/gin_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5433:8080
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  postgres_data: